name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          echo "hello"